### ISSUE TITLE
Move message being sent twice to server

### ISSUE THREAD

**Issue by ams939** [ams939/CheckersWebApp#5]
A move is occasionally sent to the server twice, on the latter move server tries to move non-existent piece and crashes

**Comment by ams939** [comment]
2019-03-09 03:16:27+0000 [-] onMessage: {"code":2,"old_pos":{"col":0,"row":0},"new_pos":{"row":1,"col":1},"session_id":"285cbf7ee59b4af2869507a79e2687f7"}
2019-03-09 03:16:27+0000 [-] {'old_pos': {'col': 0, 'row': 0}, 'new_pos': {'col': 1, 'row': 1}}
2019-03-09 03:16:27+0000 [-] [[REGULAR None None None None None None None]
2019-03-09 03:16:27+0000 [-]  [None None None None None None None None]
2019-03-09 03:16:27+0000 [-]  [None None None None REGULAR None REGULAR None]
2019-03-09 03:16:27+0000 [-]  [None REGULAR None REGULAR None None None None]
2019-03-09 03:16:27+0000 [-]  [None None None None None None None None]
2019-03-09 03:16:27+0000 [-]  [None REGULAR None None None None None REGULAR]
2019-03-09 03:16:27+0000 [-]  [None None None None None None REGULAR None]
2019-03-09 03:16:27+0000 [-]  [None KING None None None None None None]]
2019-03-09 03:16:27+0000 [-] [[None None None None None None None None]
2019-03-09 03:16:27+0000 [-]  [None REGULAR None None None None None None]
2019-03-09 03:16:27+0000 [-]  [None None None None REGULAR None REGULAR None]
2019-03-09 03:16:27+0000 [-]  [None REGULAR None REGULAR None None None None]
2019-03-09 03:16:27+0000 [-]  [None None None None None None None None]
2019-03-09 03:16:27+0000 [-]  [None REGULAR None None None None None REGULAR]
2019-03-09 03:16:27+0000 [-]  [None None None None None None REGULAR None]
2019-03-09 03:16:27+0000 [-]  [None KING None None None None None None]]
2019-03-09 03:16:27+0000 [-] ['867df0c62c05d800dff2484016bf1d67c51cbca5b07385b3d608aa72d22ad6b2', '6d0d8ee2fd68fa504112560b0c4394cee0e13857a357f44d8fc051c98753e0ed', '418fa12a66273df16e1388f7d0e563872f5376aea6a4820c4d084badf5ba022e', '0e5386f8adc270906a1b5d2a03520f6b1b0ff9f965d8b6886855e11346dfeda7', '9280961abfb936250765bb17678091a4e290f89b761875ded8cbf2580f0f50a9']
2019-03-09 03:16:27+0000 [-] {'reason': None, 'current_turn': 1, 'session_id': '285cbf7ee59b4af2869507a79e2687f7', 'board': {'board': [[None, None, None, None, None, None, None, None], [None, {'piece_type': 'REGULAR', 'owner': 2, 'coordinates': {'col': 1, 'row': 1}}, None, None, None, None, None, None], [None, None, None, None, {'piece_type': 'REGULAR', 'owner': 2, 'coordinates': {'col': 4, 'row': 2}}, None, {'piece_type': 'REGULAR', 'owner': 2, 'coordinates': {'col': 6, 'row': 2}}, None], [None, {'piece_type': 'REGULAR', 'owner': 1, 'coordinates': {'col': 1, 'row': 3}}, None, {'piece_type': 'REGULAR', 'owner': 2, 'coordinates': {'col': 3, 'row': 3}}, None, None, None, None], [None, None, None, None, None, None, None, None], [None, {'piece_type': 'REGULAR', 'owner': 1, 'coordinates': {'col': 1, 'row': 5}}, None, None, None, None, None, {'piece_type': 'REGULAR', 'owner': 1, 'coordinates': {'col': 7, 'row': 5}}], [None, None, None, None, None, None, {'piece_type': 'REGULAR', 'owner': 1, 'coordinates': {'col': 6, 'row': 6}}, None], [None, {'piece_type': 'KING', 'owner': 2, 'coordinates': {'col': 1, 'row': 7}}, None, None, None, None, None, None]]}, 'valid': True, 'winner': '', 'game_over': False, 'draw': False}
2019-03-09 03:16:34+0000 [-] onMessage: {"code":2,"old_pos":{"col":7,"row":5},"new_pos":{"row":4,"col":6},"session_id":"285cbf7ee59b4af2869507a79e2687f7"}
2019-03-09 03:16:34+0000 [-] {'old_pos': {'col': 7, 'row': 5}, 'new_pos': {'col': 6, 'row': 4}}
2019-03-09 03:16:34+0000 [-] [[None None None None None None None None]
2019-03-09 03:16:34+0000 [-]  [None REGULAR None None None None None None]
2019-03-09 03:16:34+0000 [-]  [None None None None REGULAR None REGULAR None]
2019-03-09 03:16:34+0000 [-]  [None REGULAR None REGULAR None None None None]
2019-03-09 03:16:34+0000 [-]  [None None None None None None None None]
2019-03-09 03:16:34+0000 [-]  [None REGULAR None None None None None REGULAR]
2019-03-09 03:16:34+0000 [-]  [None None None None None None REGULAR None]
2019-03-09 03:16:34+0000 [-]  [None KING None None None None None None]]
2019-03-09 03:16:34+0000 [-] [[None None None None None None None None]
2019-03-09 03:16:34+0000 [-]  [None REGULAR None None None None None None]
2019-03-09 03:16:34+0000 [-]  [None None None None REGULAR None REGULAR None]
2019-03-09 03:16:34+0000 [-]  [None REGULAR None REGULAR None None None None]
2019-03-09 03:16:34+0000 [-]  [None None None None None None REGULAR None]
2019-03-09 03:16:34+0000 [-]  [None REGULAR None None None None None None]
2019-03-09 03:16:34+0000 [-]  [None None None None None None REGULAR None]
2019-03-09 03:16:34+0000 [-]  [None KING None None None None None None]]
2019-03-09 03:16:34+0000 [-] ['6d0d8ee2fd68fa504112560b0c4394cee0e13857a357f44d8fc051c98753e0ed', '418fa12a66273df16e1388f7d0e563872f5376aea6a4820c4d084badf5ba022e', '0e5386f8adc270906a1b5d2a03520f6b1b0ff9f965d8b6886855e11346dfeda7', '9280961abfb936250765bb17678091a4e290f89b761875ded8cbf2580f0f50a9']
2019-03-09 03:16:34+0000 [-] {'reason': None, 'current_turn': 2, 'session_id': '285cbf7ee59b4af2869507a79e2687f7', 'board': {'board': [[None, None, None, None, None, None, None, None], [None, {'piece_type': 'REGULAR', 'owner': 2, 'coordinates': {'col': 1, 'row': 1}}, None, None, None, None, None, None], [None, None, None, None, {'piece_type': 'REGULAR', 'owner': 2, 'coordinates': {'col': 4, 'row': 2}}, None, {'piece_type': 'REGULAR', 'owner': 2, 'coordinates': {'col': 6, 'row': 2}}, None], [None, {'piece_type': 'REGULAR', 'owner': 1, 'coordinates': {'col': 1, 'row': 3}}, None, {'piece_type': 'REGULAR', 'owner': 2, 'coordinates': {'col': 3, 'row': 3}}, None, None, None, None], [None, None, None, None, None, None, {'piece_type': 'REGULAR', 'owner': 1, 'coordinates': {'col': 6, 'row': 4}}, None], [None, {'piece_type': 'REGULAR', 'owner': 1, 'coordinates': {'col': 1, 'row': 5}}, None, None, None, None, None, None], [None, None, None, None, None, None, {'piece_type': 'REGULAR', 'owner': 1, 'coordinates': {'col': 6, 'row': 6}}, None], [None, {'piece_type': 'KING', 'owner': 2, 'coordinates': {'col': 1, 'row': 7}}, None, None, None, None, None, None]]}, 'valid': True, 'winner': '', 'game_over': False, 'draw': False}
2019-03-09 03:16:34+0000 [-] onMessage: {"code":2,"old_pos":{"col":7,"row":5},"new_pos":{"row":4,"col":6},"session_id":"285cbf7ee59b4af2869507a79e2687f7"}
2019-03-09 03:16:34+0000 [-] {'old_pos': {'col': 7, 'row': 5}, 'new_pos': {'col': 6, 'row': 4}}
2019-03-09 03:16:34+0000 [-] [[None None None None None None None None]
2019-03-09 03:16:34+0000 [-]  [None REGULAR None None None None None None]
2019-03-09 03:16:34+0000 [-]  [None None None None REGULAR None REGULAR None]
2019-03-09 03:16:34+0000 [-]  [None REGULAR None REGULAR None None None None]
2019-03-09 03:16:34+0000 [-]  [None None None None None None REGULAR None]
2019-03-09 03:16:34+0000 [-]  [None REGULAR None None None None None None]
2019-03-09 03:16:34+0000 [-]  [None None None None None None REGULAR None]
2019-03-09 03:16:34+0000 [-]  [None KING None None None None None None]]
2019-03-09 03:16:34+0000 [CheckersProtocol,1,192.168.1.1] Unhandled Error
        Traceback (most recent call last):
          File "/home/pi/.local/lib/python3.5/site-packages/twisted/python/log.py", line 103, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/home/pi/.local/lib/python3.5/site-packages/twisted/python/log.py", line 86, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/home/pi/.local/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/home/pi/.local/lib/python3.5/site-packages/twisted/python/context.py", line 85, in callWithContext
            return func(*args,**kw)
        --- <exception caught here> ---
          File "/home/pi/.local/lib/python3.5/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
            why = selectable.doRead()
          File "/home/pi/.local/lib/python3.5/site-packages/twisted/internet/tcp.py", line 243, in doRead
            return self._dataReceived(data)
          File "/home/pi/.local/lib/python3.5/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
            rval = self.protocol.dataReceived(data)
          File "/home/pi/.local/lib/python3.5/site-packages/autobahn/twisted/websocket.py", line 135, in dataReceived
            self._dataReceived(data)
          File "/home/pi/.local/lib/python3.5/site-packages/autobahn/websocket/protocol.py", line 1182, in _dataReceived
            self.consumeData()
          File "/home/pi/.local/lib/python3.5/site-packages/autobahn/websocket/protocol.py", line 1194, in consumeData
            while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
          File "/home/pi/.local/lib/python3.5/site-packages/autobahn/websocket/protocol.py", line 1560, in processData
            fr = self.onFrameEnd()
          File "/home/pi/.local/lib/python3.5/site-packages/autobahn/websocket/protocol.py", line 1682, in onFrameEnd
            self._onMessageEnd()
          File "/home/pi/.local/lib/python3.5/site-packages/autobahn/twisted/websocket.py", line 163, in _onMessageEnd
            self.onMessageEnd()
          File "/home/pi/.local/lib/python3.5/site-packages/autobahn/websocket/protocol.py", line 628, in onMessageEnd
            self._onMessage(payload, self.message_is_binary)
          File "/home/pi/.local/lib/python3.5/site-packages/autobahn/twisted/websocket.py", line 166, in _onMessage
            self.onMessage(payload, isBinary)
          File "main.py", line 219, in onMessage
            self.handleMessage(payload)
          File "main.py", line 235, in handleMessage
            _events.get(message['code'], invalidData)(self.player, message)
          File "main.py", line 81, in handleMovePiece
            is_valid, reason = sess.handle_move(move)
          File "/home/pi/Documents/School/CheckersWebApp/Server/GameSession.py", line 70, in handle_move
            if vd.validate(move, self.board):
          File "/home/pi/Documents/School/CheckersWebApp/Server/Validator.py", line 23, in validate
            player = (board.get_piece_at(old_pos)).owner
        builtins.AttributeError: 'NoneType' object has no attribute 'owner'

2019-03-09 03:16:34+0000 [-] Username: significantotter is now available
2019-03-09 03:16:34+0000 [-] Player tried to leave queue but wasn't in queue
2019-03-09 03:16:34+0000 [-] {'285cbf7ee59b4af2869507a79e2687f7': <GameSession.GameSession object at 0x75080eb0>}
2019-03-09 03:16:34+0000 [-] significantotter has quit match with session id: 285cbf7ee59b4af2869507a79e2687f7
2019-03-09 03:16:34+0000 [-] Session no longer exists
2019-03-09 03:16:34+0000 [-] {}
2019-03-09 03:16:34+0000 [-] WebSocket connection closed: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)
2019-03-09 03:16:37+0000 [-] Username: LilMya is now available
2019-03-09 03:16:37+0000 [-] Player tried to leave queue but wasn't in queue
2019-03-09 03:16:37+0000 [-] WebSocket connection closed: None
2019-03-09 03:16:37+0000 [-] tcp4:192.168.1.1:36376 connected
2019-03-09 03:16:37+0000 [-] onMessage: {"code":5,"username":"LilMya"}
2019-03-09 03:16:37+0000 [-] Player is now known as LilMya

**Comment by ams939** [comment]
Looks like the "onMessage" function is called twice. client console log shows that client only sent message once

**Comment by bastump987** [comment]
@ams939 I think you mentioned on Discord that this is fixed, correct?  If so, can we close this issue out?

**Comment by ams939** [comment]
@bastump987 yes, I'll close the issue now
